services:
- docker
script:
- bash create-binary-docker backend
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- docker push cklopp/backend-amd64
env:
  matrix:
    secure: cHIi54mGdjzachiuupzdWn4IbHRM5Bl8HEKYgAgYV+IlIYjMy3wf4klDbTSCIQv/mpeuvbUZOT7ffFVpVEWIJCDGsVPuFOjCXC3K/wJBvvY2+es6ALhjsWfplQg9dic4CnACX+6PiBonFElnZeBs/TTF2ABDah9LSzwWN0HFW8difgU4c8+uOdCZj4IAfV73cOmKd4+I2VjsJbb3LE9VEeL6rVBV+WFArvpuZ1UxJOEWPibKDtWQoyl4P6lw5Wzd71IQ9MZFq7Q640CWs8o+tXE6fYr8oyEw4iWfayH6TCvLsJV5C6WEukiAVfQrDuNed7A2MvYt44CjxL286c8U9e/WMcVy8umscBVXCmxZzyanc8J/BUi9dgYmFbUGYRUQo/7xLUOlA7TIkjVwCVtXnYWf9w8RZLd2Z7s4gPxQLwXCaaW4fJocufLnkrD65G5n8INZ+wwSjqdQ1UuVEZ7frWDWbGNVZ7pbteQ24BR81ln1vEyNdCBtqdzZGpTZ2GrgivE0ssBSzTR3o6lJis+UIElgeysCIt5LJzFnVYwTAgwiyygTIr96gpzhmf56p7FjdlbjNls1FNJkHOgldQ5LEBGXPfSREOyJXlKzOdN0ACfIm9tX2XThdnM1l05brDaaYkMKVd3qoptTW9MQSFtVHt5woUrEwFgLnnaTnIyrUhk=
