services:
- docker
script:
- bash "create-binary-docker backend"
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- docker push cklopp/backend-amd64
env:
  matrix:
  - secure: Dfhr0oC4i4H4YX3saxbzPh97CPoSUoxwLCK+MxQ7y1aYZSui1Vcsp0xyvPPh3Q/MDWYbQG1S0eU+gT3u4CCD+WLX2TMNt9TxXIDdxrCXUK3Tx/+hut2T/viyubd9aBttEXBmFOi1WrDIdq+1vs6RQJy3j1PwdUHkewB+SB36xEJdHBFQQS5EmbggBAtw8HcYIrt6UJfYktikHg4Phq8tO9sjKgcMfRXKFHp5ipzW9e7uaAVWhHWW21rJKUpivpH+Q9l9bI/fOrYrJmbFH689mLitSMHUkzRdAbVW3DFLEu8NoJe/y3IT8x5JiFNnFn6pLkuefAR4f0PJzH0ELIm6N7EycBJdiYoXFBfRZX9+MpPWOO8lCH4v1tZK6Sj/D7mqJvpzzECGhZ8lQfcl8559sQuXX1JXXeRihpVBdNVkJGqHlMCtnwbSXCtwJBDM4T8PL19Me9cjOTDGkIT8Esel+k7de/2nJHHKrPTzaYChNtJVlZhaVjSkXWieGfL/qqEpxSrYQzIVWwTZO6/Il40i8lxk5YxZ6o9X5c9mSsCpMn8+NojWS7J6cSg4iPUj38QaiqUoRI+N1kOh2ymbM7h6wkLzhNxodIL8CNMNdBjFgzlVotfCyDcnxcpHL0mQeKHwz0tmcRCVFng8Ef5rtViRdgY7mi0In0osQbj7aHkW0TU=
