services:
  - docker
script:
  - bash "create-binary-docker backend"
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push cklopp/backend-amd64
env:
  matrix:
  - secure: sIBfxPC+7J/f9Pm5FzsY6GPe2AUhrAsfEx8qYvlcOlotxsdf02Q7yKR/nmhi63k90tCkawIKSpq5k/KN4XqIMjF6BcY9RzzMl60e+7d6Us1KkPbYUH6uvMW9pjCTwn+g1btPFlfy4EAA5kj9rUlbjiCeDc1kH3PE1bzEVAVH0umdGBLhzakbiVDMYICrVBrNmhBMZjbUM2LX2sGufhLqd4fhzR2azMPAe/Xh/tYYiyg6ShfpRCxYVzUzEik4JcRJEtijyeB4ogRcXm7VvI4GJ1JqFGKxs912Z3Rk1TLB2qotAFdDzcoDRuAqMKMp/zcmS8J7oInd+1IPmIzUQNiWuI6hKwz3O0gPJXYWbHXy3TRKdItvxSaIRxD6/qN1prKeRknfI5v4y/DACuDRZtJchz2VIsd2dC46/wUX8N3lfQxPL6akT62AgJm+aTFBNDOEOa8Ff7L9Y7JxvXAF3irT1BzLafcAlW5ZpGZcvTwiYJ4UfT4gMS/Gf/qTh58DWX4dQGyJZeC90sz9JohDZ9X8SL5Ovdz9pMn/vFpPB4xp3nJTX6Bi+57ePZxEMLzvqs5lxRypi6z1PnZvL6HSjViGoG+5Ew+H0U5cVu7qNayHh/1Msy4MyO5rFzYLtDebenCffTahnSsI6p957FWdQ3WjwV3xi182bHMyxyyNc/IuqlQ=
